
# Server Configuration
server:
  port: 8300
spring:
  application:
    name: USER-SERVICE

  # Database Properties
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/shopping_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Config Server
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}

  # OKTA client
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-60234677.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oajutv11yU0bi6MP5d7
            client-secret: z5pkRQTBrxnxhexRess4C_TSv_0jBIzqwEHfxnw4S1_Qw9VU_zOeskOPRsOTUOdM
        provider:
          okta:
            issuer-uri: https://dev-60234677.okta.com/oauth2/default

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED


# Uncomment the following properties if needed for external circuit breaker
# resilience4j:
#   circuitbreaker:
#     instances:
#       external:
#         event-consumer-buffer-size: 10
#         failure-rate-threshold: 50
#         minimum-number-of-calls: 5
#         automatic-transition-from-open-to-half-open-enabled: true
#         wait-duration-in-open-state: 5s
#         permitted-number-of-calls-in-half-open-state: 3
#         sliding-window-size: 10
#         sliding-window-type: COUNT_BASED











# spring.application.name=USER-SERVICE
# # Port on which application will run
# server.port=8300

# # Database properties
# spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/shopingdb
# spring.datasource.username=root
# spring.datasource.password=root
# spring.datasource.driver-class-name=com.mysql.jdbc.Driver

# # Create and drop table if entity changes
# spring.jpa.hibernate.ddl-auto=update

# # Show SQL queries in Logs
# spring.jpa.show-sql=true

# #GIT LINK TO FETCH EUREKA properties
# spring.config.import=configserver:http://localhost:9296

# # resilience4j.circuitbreaker.instances.external.event-consumer-buffer-size=10
# # resilience4j.circuitbreaker.instances.external.failure-rate-threshold=50
# # resilience4j.circuitbreaker.instances.external.minimum-number-of-calls=5
# # resilience4j.circuitbreaker.instances.external.automatic-transition-from-open-to-half-open-enabled=true
# # resilience4j.circuitbreaker.instances.external.wait-duration-in-open-state=5s
# # resilience4j.circuitbreaker.instances.external.permitted-number-of-calls-in-half-open-state=3
# # resilience4j.circuitbreaker.instances.external.sliding-window-size=10
# # resilience4j.circuitbreaker.instances.external.sliding-window-type=COUNT_BASED

# resilience4j.circuitbreaker.instances.external.registerHealthIndicator=true
# resilience4j.circuitbreaker.instances.external.slidingWindowSize=5
# resilience4j.circuitbreaker.instances.external.failureRateThreshold=50
# resilience4j.circuitbreaker.instances.external.waitDurationInOpenState=10000


# # OKTA
# # OKTA client
# spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-60234677.okta.com/oauth2/default
# spring.security.oauth2.client.registration.internal-client.provider=okta
# spring.security.oauth2.client.registration.internal-client.authorization-grant-type=client_credentials
# spring.security.oauth2.client.registration.internal-client.scope=internal
# spring.security.oauth2.client.registration.internal-client.client-id=0oajutv11yU0bi6MP5d7
# spring.security.oauth2.client.registration.internal-client.client-secret=z5pkRQTBrxnxhexRess4C_TSv_0jBIzqwEHfxnw4S1_Qw9VU_zOeskOPRsOTUOdM

# spring.security.oauth2.client.provider.okta.issuer-uri=https://dev-60234677.okta.com/oauth2/default