spring:
  application:
    name: ORDER-SERVICE

  # Server configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306}/shopping_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    show-sql: true

  # Config server link to fetch Eureka properties
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9296}

  # OKTA configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-60234677.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oajutv11yU0bi6MP5d7
            client-secret: z5pkRQTBrxnxhexRess4C_TSv_0jBIzqwEHfxnw4S1_Qw9VU_zOeskOPRsOTUOdM
        provider:
          okta:
            issuer-uri: https://dev-60234677.okta.com/oauth2/default

# Server port configuration
server:
  port: 8200


resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
